#name: 'user-web'
#port: 8021
#user_srv:
#  host: '127.0.0.1'
#  port: 50051
#  name: 'user-srv'
#redis:
#  host: '192.168.0.104'
#  port: 6379
#  expire: 300
#consul:
#  host: '192.168.0.104'
#  port: 8500

# nacos配置
host: '192.168.0.104'
port: 8848
namespace: '5ed0d643-e595-4d90-95ee-8808a6323f62'
user: 'nacos'
password: 'nacos'
dataid: 'user-web.json'
group: 'dev'
