#name: 'user-srv'
#mysql:
#  host: '192.168.0.104'
#  db: 'shop_user_srv'
#  port: 3306
#  password: 'root'
#  user: 'root'
#consul:
#  host: '192.168.0.104'
#  port: 8500
host: '192.168.0.104'
port: 8848
namespace: '5ed0d643-e595-4d90-95ee-8808a6323f62'
user: 'nacos'
password: 'nacos'
dataid: 'user-srv.json'
group: 'dev'
